=== ElPediatra/1-DAW/Alberto_Lenguajes/Segundo_Trimestre/PaisesUnion/PaisesUnion_GomezMorales_Alberto.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="CodigoPais">
    <xs:restriction base="xs:string">
      <xs:pattern value="\+?[0-9]{2,3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NombrePais">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EspaÃ±a"/>
      <xs:enumeration value="Francia"/>
      <xs:enumeration value="Alemania"/>
      <xs:enumeration value="Italia"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Pais">
    <xs:union memberTypes="NombrePais CodigoPais"/>
  </xs:simpleType>

  <xs:element name="direccion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="calle" type="xs:string"/>
        <xs:element name="ciudad" type="xs:string"/>
        <xs:element name="codigo-postal" type="xs:string"/>
        <xs:element name="region" type="xs:string"/>
        <xs:element name="pais" type="Pais"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="paises">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="direccion" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ElPediatra/1-DAW/Alberto_Lenguajes/Segundo_Trimestre/PaisesUnion/PaisesUnion_GomezMorales_Alberto.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Crear una restriccion para utilizar la union en xsd, de forma que en el elemento <pais> 
pueda contener tanto el nombre del pais como su código
Poner en la restriccion 4 paises y 4 códigos-->

<paises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="PaisesUnion_GomezMorales_Alberto.xsd">
 <direccion>
    <calle> Avda Los Castros</calle>
    <ciudad>Santander</ciudad>
    <codigo-postal>39005</codigo-postal>
    <region>Cantabria</region>
    <pais>España</pais>
  </direccion>

  <direccion>
    <calle> Los Larios</calle>
    <ciudad>Malaga</ciudad>
    <codigo-postal>29005</codigo-postal>
    <region>Andalucia</region>
    <pais>+34</pais>
  </direccion>

  <direccion>
    <calle> Le Etage</calle>
    <ciudad>Paris</ciudad>
    <codigo-postal>00046</codigo-postal>
    <region>Centro</region>
    <pais>Francia</pais>
  </direccion>

  <direccion>
    <calle> La herreria</calle>
    <ciudad>Paris</ciudad>
    <codigo-postal>00046</codigo-postal>
    <region>Norte</region>
    <pais>+33</pais>
  </direccion>

  <direccion>
    <calle> Avda del Pilar</calle>
    <ciudad>Zaragoza</ciudad>
    <codigo-postal>52005</codigo-postal>
    <region>Aragon</region>
    <pais>España</pais>
  </direccion>

  <direccion>
    <calle> Alba De Tormes</calle>
    <ciudad>Avila</ciudad>
    <codigo-postal>05005</codigo-postal>
    <region>CastillaLeon</region>
    <pais>+34</pais>
  </direccion>
</paises>
