=== ElPediatra/1-DAW/Alberto_Lenguajes/Examenes/Segundo_Trimestre/Examen XML/Ejercicio1_GomezMorales_Alberto.dtd
<!-- Pedido debe tener un cliente y producto-->
<!ELEMENT pedido (cliente, productos)>

<!-- Cliente debe tener el nombre del cliente y su dirección-->
<!ELEMENT cliente (nombre, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

<!-- El pedido/producto puede tener varios productos con su nombre, precio y cantidad, pongo que sean necesarios ya que no tiene sentido un pedido vacío-->
<!ELEMENT productos (producto+)>
<!ELEMENT producto EMPTY>
<!ATTLIST producto
          nombre CDATA #REQUIRED
          precio CDATA #REQUIRED
          cantidad CDATA #REQUIRED>

=== ElPediatra/1-DAW/Alberto_Lenguajes/Examenes/Segundo_Trimestre/Examen XML/Ejercicio1_GomezMorales_Alberto.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Alberto Gómez Morales - 1º DAW - Lenguajes de Marcas y Sistemas de Gestión de Información

    Ejercicio 1.- Crea un documento XML que represente un pedido de una hamburguesería. La
    información contenida es: nombre del cliente, una lista de productos que incluya el
    nombre y el precio. Por cada producto, incluye un atributo que contenga el número de
    productos. Realiza un DTD externo que valide el formato del documento XML.
-->

<!-- Asociación al archivo DTD -->
<!DOCTYPE pedido SYSTEM "Ejercicio1_GomezMorales_Alberto.dtd">

<!-- Sección general del pedido -->
<pedido>
  <!-- Información del cliente -->
  <cliente>
    <nombre>Marvin y Nemo</nombre>
    <direccion>Calle Wallaby 46, Sidney</direccion>
  </cliente>

  <!-- Información de los productos -->
  <productos>
    <producto nombre="Hamburguesa de pollo" precio="2" cantidad="2"/>
    <producto nombre="Hamburguesa vegana" precio="4" cantidad="1"/>
    <producto nombre="Patatas fritas grandes" precio="3,50" cantidad="2"/>
    <producto nombre="Patatas fritas pequeñas" precio="1,20" cantidad="1"/>
    <producto nombre="Cubo de nuggets" precio="8,20" cantidad="1"/>
    <producto nombre="Cerveza" precio="5" cantidad="2"/>
    <producto nombre="Refresco pequeño" precio="1,50" cantidad="1"/>
  </productos>
</pedido>
