=== ElPediatra/1-DAW/Alberto_Lenguajes/Segundo_Trimestre/AlumnosMas Key/AlumnosMas_GomezMorales_Alberto.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cursos" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="aula">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="9"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="curso" type="xs:string"/>
            </xs:sequence>
            <xs:key name="pk_curso">
              <xs:selector xpath="."/>
              <xs:field xpath="curso"/>
            </xs:key>
          </xs:complexType>
        </xs:element>
        <xs:element name="alumno" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="curso">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="B2"/>
                    <xs:enumeration value="B3"/>
                    <xs:enumeration value="C1"/>
                    <xs:enumeration value="C2"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="dni">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\d{8}[A-Z]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="numero_de_matricula">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="1000"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="delegado" type="xs:boolean"/>
            </xs:sequence>
            <xs:key name="pk_alumno">
              <xs:selector xpath="."/>
              <xs:field xpath="dni"/>
            </xs:key>
            <xs:keyref name="fk_alumno_curso" refer="pk_curso">
              <xs:selector xpath="."/>
              <xs:field xpath="curso"/>
            </xs:keyref>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ElPediatra/1-DAW/Alberto_Lenguajes/Segundo_Trimestre/AlumnosMas Key/AlumnosMas_GomezMorales_Alberto.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Crear el fichero .xsd con las claves primarias y claves ajenas sabiendo que los alumnos realizan los cursos 
y en un curso puede haber más de un alumno. Insertar en el fichero .xml los campos para dichas claves si es necesario. 
* Restricción en el curso
* Restriccion de las aulas conociendo que se enumeran del 1 al 9
* Restricción del DNi
* Restriccion de la matricula que tiene un máximo de 1000 y no es negativo
-->

<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="AlumnosMas_GomezMorales_Alberto.xsd" version="1.0">
    <cursos> 
        <aula>2</aula>  
        <curso>B2</curso>
    </cursos>
    <cursos> 
        <aula>3</aula>  
        <curso>B3</curso>
    </cursos>
    <cursos> 
        <aula>1</aula>  
        <curso>C1</curso>
    </cursos>
    <cursos> 
        <aula>5</aula>  
        <curso>C2</curso>
    </cursos>
    <alumno id="1">
        <curso>B3</curso>
        <dni>12345678M</dni>
        <nombre>Maria</nombre>
        <numero_de_matricula>100</numero_de_matricula>
        <delegado>Falso</delegado>  
    </alumno>
    <alumno id="2">
        <curso>B2</curso>
        <dni>44555666V</dni>
        <nombre>Juan</nombre>
        <numero_de_matricula>606</numero_de_matricula>
        <delegado>Verdadero</delegado>  
    </alumno>
    <alumno id="3">
        <curso>B3</curso>
        <dni>56798765R</dni>
        <nombre>Antonio</nombre>
        <numero_de_matricula>111</numero_de_matricula>
        <delegado>Falso</delegado>  
    </alumno>
    <alumno id="4">
        <curso>C1</curso>
        <dni>98765400R</dni>
        <nombre>Juan</nombre>
        <numero_de_matricula>222</numero_de_matricula>
        <delegado>Verdadero</delegado>  
    </alumno>
    <alumno id="5">
        <curso>C1</curso>
        <dni>55443300T</dni>
        <nombre>Marta</nombre>
        <numero_de_matricula>120</numero_de_matricula>
        <delegado>Falso</delegado>  
    </alumno>
</alumnos>
